#!/bin/sh

wget ftp://ftp.perforce.com/perforce/r19.1/bin.linux26x86_64/p4d
chmod +x p4d
sudo adduser perforce
sudo chown perforce p4d

sudo mkdir /home/perforce
sudo mkdir /home/perforce/depot
sudo mkdir /home/perforce/log
sudo mkdir /home/perforce/journal

sudo chown perforce /home/perforce
sudo chown perforce /home/perforce/depot
sudo chown perforce /home/perforce/log
sudo chown perforce /home/perforce/journal

sudo mv p4d /home/perforce

cd /etc/systemd/system
wget https://raw.githubusercontent.com/Skylonxe/linux-perforce-installer/master/p4d.service

systemctl enable p4d

sudo reboot
